---
abstract: 'Business::ISP:: core modules'
author:
  - 'Steve Bertrand <steveb@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120530'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-ISP
no_index:
  directory:
    - t
    - inc
requires:
  Business::ISP::RADIUS: 0.02
  CGI::Application: 0
  CGI::Application::Plugin::Forward: 0
  CGI::Application::Plugin::LinkIntegrity: 0
  CGI::Application::Plugin::PageBuilder: 0
  CGI::Application::Plugin::Session: 0
  CGI::HTMLError: 0
  Config::Tiny: 0
  Cwd: 0
  DBD::mysql: 0
  DBI: 0
  DBIx::Class: 0
  DBIx::Recordset: 0
  Data::Types: 0
  DateTime: 0
  Exact::Transaction: 0
  HTML::Menu::Select: 0
  MIME::Lite::TT: 0
  Test::More: 0
resources:
  bugtracker: https://bitbucket.org/spek/isp/issues
  repository: https://bitbucket.org/spek/isp
version: 0.13_02
